#! /bin/bash

echo "Backup old environment"
BACKUP_DIR=~/backup-${date "%Y%m%d-%H%M%S"}
if [ ! -d ${BACKUP_DIR} ]; then
  mkdir ${BACKUP_DIR}
fi
if [ -d ${BACKUP_DIR}; then
  cp .bashrc ${BACKUP_DIR}/dotbashrc
  cp .bash_aliases ${BACKUP_DIR}/dotbashaliases
  cp .bash_functions ${BACKUP_DIR}/dotbashfunctions
  cp .tmux.conf ${BACKUP_DIR}/dottmuxconf
fi

echo "Installing new environment"
cp .bashrc ~/.bashrc
cp .bash_aliases ~/.bash_aliases
cp .bash_functions ~/.bash_functions

